// 由 samples/graph3d.py 自动生成（勿手改）：python3 tools/py2c.py samples/graph3d.py graph3d_py > System/applications/user/pyapp/graph3d_py.c

const char *graph3d_py_version = "graph3d.py v2026-10-08";
const char *graph3d_py_source =
    "# graph3d.py v2026-10-08 - minimal 3D plotting module for the ExistOS Python app\n"
    "#\n"
    "# ASCII-only source (MicroPython reads UTF-8; the LCD font is GBK-indexed).\n"
    "# 1bpp screen: wireframe rendering (lines), no shading.\n"
    "#\n"
    "# API:\n"
    "#   clf()                                 clear the current figure\n"
    "#   surface(f, x0, x1, y0, y1, n=14)      z = f(x, y) over a grid (wireframe mesh)\n"
    "#   plot(xs, ys, zs)                      3D polyline from three sequences\n"
    "#   view(az, el)                          camera angles in degrees (default 45, 30)\n"
    "#   title(s)                              figure title (ASCII)\n"
    "#   show()                                render full screen; L/R rotate, U/D tilt,\n"
    "#                                         ON/F5 back to the terminal\n"
    "#\n"
    "# Example:\n"
    "#   import graph3d, math\n"
    "#   graph3d.surface(lambda x, y: math.sin(x) * math.cos(y), -3, 3, -3, 3)\n"
    "#   graph3d.show()\n"
    "\n"
    "import framebuf\n"
    "import lcd\n"
    "import math\n"
    "\n"
    "_TOP = 14            # leave the top icon row to the system\n"
    "_BAR = 12            # bottom hint line\n"
    "\n"
    "_g = None\n"
    "\n"
    "\n"
    "class _Graph3d(object):\n"
    "    def __init__(self):\n"
    "        self.w = lcd.width()\n"
    "        self.h = lcd.height()\n"
    "        self.px0 = 0\n"
    "        self.py0 = _TOP\n"
    "        self.pw = self.w\n"
    "        self.ph = self.h - _TOP - _BAR\n"
    "        self.segs = []          # flat list of (x1,y1,z1,x2,y2,z2)\n"
    "        self._title = \"\"\n"
    "        self.az = 45.0          # azimuth (rotation, degrees)\n"
    "        self.el = 30.0          # elevation (tilt, degrees)\n"
    "        self.cx = self.cy = self.cz = 0.0\n"
    "        self.inv = 1.0\n"
    "\n"
    "    # ---------- figure state ----------\n"
    "    def clf(self):\n"
    "        self.segs = []\n"
    "        self._title = \"\"\n"
    "        self.az = 45.0\n"
    "        self.el = 30.0\n"
    "\n"
    "    def title(self, s):\n"
    "        self._title = s\n"
    "\n"
    "    def view(self, az, el):\n"
    "        self.az = float(az) % 360.0\n"
    "        el = float(el)\n"
    "        if el > 89.0:\n"
    "            el = 89.0\n"
    "        if el < -89.0:\n"
    "            el = -89.0\n"
    "        self.el = el\n"
    "\n"
    "    # ---------- data ----------\n"
    "    def surface(self, f, x0, x1, y0, y1, n=14):\n"
    "        x0 = float(x0)\n"
    "        x1 = float(x1)\n"
    "        y0 = float(y0)\n"
    "        y1 = float(y1)\n"
    "        n = int(n)\n"
    "        if n < 4:\n"
    "            n = 4\n"
    "        if n > 30:\n"
    "            n = 30\n"
    "        if x1 <= x0 or y1 <= y0:\n"
    "            raise ValueError(\"bad range\")\n"
    "        zs = []\n"
    "        i = 0\n"
    "        while i < n:\n"
    "            x = x0 + (x1 - x0) * i / (n - 1)\n"
    "            row = []\n"
    "            j = 0\n"
    "            while j < n:\n"
    "                y = y0 + (y1 - y0) * j / (n - 1)\n"
    "                row.append(float(f(x, y)))\n"
    "                j += 1\n"
    "            zs.append(row)\n"
    "            i += 1\n"
    "        # mesh: lines along x and along y\n"
    "        i = 0\n"
    "        while i < n:\n"
    "            x = x0 + (x1 - x0) * i / (n - 1)\n"
    "            j = 0\n"
    "            while j < n - 1:\n"
    "                ya = y0 + (y1 - y0) * j / (n - 1)\n"
    "                yb = y0 + (y1 - y0) * (j + 1) / (n - 1)\n"
    "                self.segs.append((x, ya, zs[i][j], x, yb, zs[i][j + 1]))\n"
    "                self.segs.append((ya, x, zs[j][i], yb, x, zs[j + 1][i]))\n"
    "                j += 1\n"
    "            i += 1\n"
    "\n"
    "    def plot(self, xs, ys, zs):\n"
    "        if xs is None or ys is None or zs is None:\n"
    "            raise ValueError(\"x/y/z required\")\n"
    "        if len(xs) != len(ys) or len(xs) != len(zs) or len(xs) < 2:\n"
    "            raise ValueError(\"x/y/z must be sequences of equal length (>= 2)\")\n"
    "        i = 1\n"
    "        while i < len(xs):\n"
    "            self.segs.append((float(xs[i - 1]), float(ys[i - 1]), float(zs[i - 1]),\n"
    "                              float(xs[i]), float(ys[i]), float(zs[i])))\n"
    "            i += 1\n"
    "\n"
    "    # ---------- projection ----------\n"
    "    def _bounds(self):\n"
    "        if not self.segs:\n"
    "            return\n"
    "        xmin = xmax = self.segs[0][0]\n"
    "        ymin = ymax = self.segs[0][1]\n"
    "        zmin = zmax = self.segs[0][2]\n"
    "        for s in self.segs:\n"
    "            for k in range(0, 6, 3):\n"
    "                x = s[k]\n"
    "                y = s[k + 1]\n"
    "                z = s[k + 2]\n"
    "                if x < xmin:\n"
    "                    xmin = x\n"
    "                if x > xmax:\n"
    "                    xmax = x\n"
    "                if y < ymin:\n"
    "                    ymin = y\n"
    "                if y > ymax:\n"
    "                    ymax = y\n"
    "                if z < zmin:\n"
    "                    zmin = z\n"
    "                if z > zmax:\n"
    "                    zmax = z\n"
    "        self.cx = (xmin + xmax) * 0.5\n"
    "        self.cy = (ymin + ymax) * 0.5\n"
    "        self.cz = (zmin + zmax) * 0.5\n"
    "        ext = xmax - xmin\n"
    "        if ymax - ymin > ext:\n"
    "            ext = ymax - ymin\n"
    "        if zmax - zmin > ext:\n"
    "            ext = zmax - zmin\n"
    "        if ext < 1e-12:\n"
    "            ext = 1e-12\n"
    "        self.inv = 1.0 / ext\n"
    "        self.axs = ((xmin, xmax), (ymin, ymax), (zmin, zmax))\n"
    "\n"
    "    def _proj(self, x, y, z):\n"
    "        # normalize (common scale, no distortion), rotate around z, tilt, orthographic\n"
    "        nx = (x - self.cx) * self.inv\n"
    "        ny = (y - self.cy) * self.inv\n"
    "        nz = (z - self.cz) * self.inv\n"
    "        a = self.az * 0.017453292519943295\n"
    "        e = self.el * 0.017453292519943295\n"
    "        ca = math.cos(a)\n"
    "        sa = math.sin(a)\n"
    "        ux = ca * nx - sa * ny\n"
    "        uy = sa * nx + ca * ny\n"
    "        v = math.cos(e) * nz - math.sin(e) * uy\n"
    "        return ux, v\n"
    "\n"
    "    def _to_px(self, u, v, sc, mx, my):\n"
    "        return int(mx + u * sc + 0.5), int(my - v * sc + 0.5)\n"
    "\n"
    "    # ---------- drawing ----------\n"
    "    def _draw(self, fb):\n"
    "        sc = self.ph * 0.92\n"
    "        mx = self.px0 + self.pw * 0.5\n"
    "        my = self.py0 + self.ph * 0.5\n"
    "        # axes from the box min corner (before the data, so data draws over them)\n"
    "        if getattr(self, \"axs\", None) is not None:\n"
    "            (x0, x1), (y0, y1), (z0, z1) = self.axs\n"
    "            o = self._proj(x0, y0, z0)\n"
    "            ox, oy = self._to_px(o[0], o[1], sc, mx, my)\n"
    "            for pt, lab in ((self._proj(x1, y0, z0), \"x\"),\n"
    "                            (self._proj(x0, y1, z0), \"y\"),\n"
    "                            (self._proj(x0, y0, z1), \"z\")):\n"
    "                px, py = self._to_px(pt[0], pt[1], sc, mx, my)\n"
    "                fb.line(ox, oy, px, py, 1)\n"
    "                self._axis_labels.append((px, py, lab))\n"
    "        for s in self.segs:\n"
    "            u1, v1 = self._proj(s[0], s[1], s[2])\n"
    "            u2, v2 = self._proj(s[3], s[4], s[5])\n"
    "            x1, y1 = self._to_px(u1, v1, sc, mx, my)\n"
    "            x2, y2 = self._to_px(u2, v2, sc, mx, my)\n"
    "            fb.line(x1, y1, x2, y2, 1)\n"
    "\n"
    "    def _overlay(self):\n"
    "        # text must be drawn after lcd.blit (the 1bpp frame buffer has no text layer)\n"
    "        for x, y, lab in self._axis_labels:\n"
    "            if 0 <= x < self.w - 6 and 0 <= y < self.h - 12:\n"
    "                lcd.text(x + 2, y, lab, 12)\n"
    "        lcd.text(4, 1, self._title, 12)\n"
    "        s = \"az%d el%d\" % (int(self.az), int(self.el))\n"
    "        lcd.text(self.w - 2 - 8 * len(s), 1, s, 12)\n"
    "        lcd.text(4, self.h - _BAR, \"ON:back L/R:rot U/D:tilt\", 12)\n"
    "\n"
    "    def show(self):\n"
    "        self._bounds()\n"
    "        fb = framebuf.FrameBuffer(bytearray((self.w * self.h + 7) // 8),\n"
    "                                  self.w, self.h, framebuf.MONO_HLSB)\n"
    "        while True:\n"
    "            self._axis_labels = []\n"
    "            fb.fill(0)\n"
    "            fb.rect(0, 0, self.w, self.h, 1)\n"
    "            fb.line(0, _TOP - 1, self.w - 1, _TOP - 1, 1)\n"
    "            self._draw(fb)\n"
    "            lcd.blit(fb)\n"
    "            self._overlay()\n"
    "            k = lcd.wait_nav()\n"
    "            if k == 0:\n"
    "                return\n"
    "            if k == 1:\n"
    "                self.az -= 15.0\n"
    "            elif k == 2:\n"
    "                self.az += 15.0\n"
    "            elif k == 3:\n"
    "                self.el += 10.0\n"
    "            elif k == 4:\n"
    "                self.el -= 10.0\n"
    "            if self.el > 89.0:\n"
    "                self.el = 89.0\n"
    "            if self.el < -89.0:\n"
    "                self.el = -89.0\n"
    "\n"
    "\n"
    "# ---------- module level API ----------\n"
    "def _g_():\n"
    "    global _g\n"
    "    if _g is None:\n"
    "        _g = _Graph3d()\n"
    "    return _g\n"
    "\n"
    "\n"
    "def clf():\n"
    "    _g_().clf()\n"
    "\n"
    "\n"
    "def surface(f, x0, x1, y0, y1, n=14):\n"
    "    _g_().surface(f, x0, x1, y0, y1, n)\n"
    "\n"
    "\n"
    "def plot(xs, ys, zs):\n"
    "    _g_().plot(xs, ys, zs)\n"
    "\n"
    "\n"
    "def view(az, el):\n"
    "    _g_().view(az, el)\n"
    "\n"
    "\n"
    "def title(s):\n"
    "    _g_().title(s)\n"
    "\n"
    "\n"
    "def show():\n"
    "    _g_().show()\n"
    "\n"
;
