// 由 samples/graph.py 自动生成（勿手改；重新生成：
//   python3 -c "import pathlib;s=pathlib.Path('samples/graph.py').read_text();
//   print(chr(10).join('"'+l.replace(chr(92),chr(92)*2).replace(chr(34),chr(92)+chr(34))+'\\n"' for l in s.split(chr(10))))"

const char *graph_py_source =
    "# graph.py - a minimal plotting module for the ExistOS Python app (2026-09-23)\n"
    "#\n"
    "# ASCII-only source (MicroPython reads UTF-8; the LCD font is GBK-indexed).\n"
    "# API:\n"
    "#   clf()                     clear the current figure\n"
    "#   plot(x, y)                line plot from two sequences\n"
    "#   plot(f, a, b, n=200)      line plot of a callable over [a, b]\n"
    "#   scatter(x, y)             point plot\n"
    "#   axis(xmin, xmax, ymin, ymax)   fix the view (disables auto scaling)\n"
    "#   title(s)                  figure title (ASCII)\n"
    "#   show()                    render full screen and wait for ON/F5\n"
    "#\n"
    "# Example:\n"
    "#   import graph\n"
    "#   graph.plot(lambda t: t * t, -2, 2)\n"
    "#   graph.show()\n"
    "\n"
    "import framebuf\n"
    "import lcd\n"
    "import math\n"
    "\n"
    "_TOP = 14            # leave the top icon row to the system\n"
    "_BAR = 12            # bottom hint line\n"
    "_GRAY = 200          # unused for 1bpp, kept for clarity\n"
    "\n"
    "_g = None\n"
    "\n"
    "\n"
    "class _Graph(object):\n"
    "    def __init__(self):\n"
    "        self.w = lcd.width()\n"
    "        self.h = lcd.height()\n"
    "        self.px0 = 0\n"
    "        self.py0 = _TOP\n"
    "        self.pw = self.w\n"
    "        self.ph = self.h - _TOP - _BAR\n"
    "        self.fb = None\n"
    "        self.xmin = 0.0\n"
    "        self.xmax = 1.0\n"
    "        self.ymin = 0.0\n"
    "        self.ymax = 1.0\n"
    "        self.auto = True\n"
    "        self.xs = []\n"
    "        self.ys = []\n"
    "        self.mode = 0        # 0 = line, 1 = scatter\n"
    "        self.title = \"\"\n"
    "\n"
    "    # ---------- figure state ----------\n"
    "    def clf(self):\n"
    "        self.xs = []\n"
    "        self.ys = []\n"
    "        self.auto = True\n"
    "        self.mode = 0\n"
    "        self.title = \"\"\n"
    "\n"
    "    def axis(self, xmin, xmax, ymin, ymax):\n"
    "        if xmax > xmin and ymax > ymin:\n"
    "            self.xmin = float(xmin)\n"
    "            self.xmax = float(xmax)\n"
    "            self.ymin = float(ymin)\n"
    "            self.ymax = float(ymax)\n"
    "            self.auto = False\n"
    "\n"
    "    def title(self, s):\n"
    "        self.title = s\n"
    "\n"
    "    # ---------- data ----------\n"
    "    def plot(self, a, b=None, c=None, d=None):\n"
    "        # plot(f, lo, hi, n) or plot(xs, ys)\n"
    "        if callable(a):\n"
    "            lo = float(b)\n"
    "            hi = float(c) if c is not None else lo + 1.0\n"
    "            n = int(d) if d is not None else 200\n"
    "            if n < 2:\n"
    "                n = 2\n"
    "            xs = []\n"
    "            ys = []\n"
    "            i = 0\n"
    "            while i < n:\n"
    "                t = lo + (hi - lo) * i / (n - 1)\n"
    "                xs.append(t)\n"
    "                ys.append(a(t))\n"
    "                i += 1\n"
    "            self._set(xs, ys, 0)\n"
    "        else:\n"
    "            self._set(a, b, 0)\n"
    "\n"
    "    def scatter(self, x, y):\n"
    "        self._set(x, y, 1)\n"
    "\n"
    "    def _set(self, xs, ys, mode):\n"
    "        if xs is None or ys is None or len(xs) != len(ys) or len(xs) == 0:\n"
    "            raise ValueError(\"x/y must be non-empty sequences of equal length\")\n"
    "        self.xs = [float(v) for v in xs]\n"
    "        self.ys = [float(v) for v in ys]\n"
    "        self.mode = mode\n"
    "\n"
    "    # ---------- scaling helpers ----------\n"
    "    def _bounds(self):\n"
    "        if self.auto:\n"
    "            xmin = min(self.xs)\n"
    "            xmax = max(self.xs)\n"
    "            ymin = min(self.ys)\n"
    "            ymax = max(self.ys)\n"
    "            if xmax - xmin < 1e-12:\n"
    "                xmin -= 0.5\n"
    "                xmax += 0.5\n"
    "            if ymax - ymin < 1e-12:\n"
    "                ymin -= 0.5\n"
    "                ymax += 0.5\n"
    "            dx = (xmax - xmin) * 0.05\n"
    "            dy = (ymax - ymin) * 0.10\n"
    "            self.xmin = xmin - dx\n"
    "            self.xmax = xmax + dx\n"
    "            self.ymin = ymin - dy\n"
    "            self.ymax = ymax + dy\n"
    "        return self.xmin, self.xmax, self.ymin, self.ymax\n"
    "\n"
    "    def _mx(self, xv):\n"
    "        return int(self.px0 + (xv - self.xmin) * (self.pw - 1) / (self.xmax - self.xmin) + 0.5)\n"
    "\n"
    "    def _my(self, yv):\n"
    "        return int(self.py0 + self.ph - 1 - (yv - self.ymin) * (self.ph - 1) / (self.ymax - self.ymin) + 0.5)\n"
    "\n"
    "    @staticmethod\n"
    "    def _nice(lo, hi, want):\n"
    "        # pick \"nice\" tick step (1/2/5 * 10^k) and return the tick list\n"
    "        if hi <= lo:\n"
    "            return []\n"
    "        span = hi - lo\n"
    "        raw = span / want\n"
    "        mag = math.pow(10.0, math.floor(math.log10(raw)))\n"
    "        for m in (1.0, 2.0, 5.0, 10.0):\n"
    "            step = m * mag\n"
    "            if step >= raw:\n"
    "                break\n"
    "        ticks = []\n"
    "        t = math.ceil(lo / step) * step\n"
    "        n = 0\n"
    "        while t <= hi + step * 1e-6 and n < 40:\n"
    "            ticks.append(t)\n"
    "            t += step\n"
    "            n += 1\n"
    "        return ticks\n"
    "\n"
    "    @staticmethod\n"
    "    def _fmt(v):\n"
    "        if abs(v) < 1e-12:\n"
    "            return \"0\"\n"
    "        a = abs(v)\n"
    "        if a >= 1e5 or a < 1e-3:\n"
    "            return \"%.0e\" % v\n"
    "        if a >= 100:\n"
    "            return \"%.0f\" % v\n"
    "        if a >= 1:\n"
    "            return (\"%.2f\" % v).rstrip(\"0\").rstrip(\".\")\n"
    "        return (\"%.3f\" % v).rstrip(\"0\").rstrip(\".\")\n"
    "\n"
    "    # ---------- drawing ----------\n"
    "    def _frame(self):\n"
    "        self.fb = framebuf.FrameBuffer(bytearray((self.w * self.h + 7) // 8), self.w, self.h, framebuf.MONO_HLSB)\n"
    "        self.fb.fill(0)                                                       # background\n"
    "        self.fb.rect(0, 0, self.w, self.h, 1)\n"
    "        self.fb.line(0, _TOP - 1, self.w - 1, _TOP - 1, 1)\n"
    "\n"
    "    def _axes(self):\n"
    "        fb = self.fb\n"
    "        x0y = self._my(0.0) if self.ymin < 0 < self.ymax else self.py0 + self.ph - 1\n"
    "        y0x = self._mx(0.0) if self.xmin < 0 < self.xmax else self.px0\n"
    "        if x0y < self.py0:\n"
    "            x0y = self.py0\n"
    "        if x0y > self.py0 + self.ph - 1:\n"
    "            x0y = self.py0 + self.ph - 1\n"
    "        fb.line(self.px0, x0y, self.px0 + self.pw - 1, x0y, 1)                # x axis\n"
    "        fb.line(y0x, self.py0, y0x, self.py0 + self.ph - 1, 1)                # y axis\n"
    "        # x ticks\n"
    "        tx = self._nice(self.xmin, self.xmax, 4)\n"
    "        for t in tx:\n"
    "            px = self._mx(t)\n"
    "            if px < self.px0 or px >= self.px0 + self.pw:\n"
    "                continue\n"
    "            fb.line(px, x0y - 2, px, x0y + 2, 1)\n"
    "            s = self._fmt(t)\n"
    "            lcd.text(px - 4 * len(s), x0y - 12, s, 12)\n"
    "        # y ticks\n"
    "        ty = self._nice(self.ymin, self.ymax, 4)\n"
    "        for t in ty:\n"
    "            py = self._my(t)\n"
    "            if py < self.py0 or py >= self.py0 + self.ph:\n"
    "                continue\n"
    "            fb.line(y0x - 2, py, y0x + 2, py, 1)\n"
    "            s = self._fmt(t)\n"
    "            lx = y0x + 3\n"
    "            if lx + 6 * len(s) > self.w - 1:\n"
    "                lx = y0x - 3 - 6 * len(s)\n"
    "            lcd.text(lx, py - 12, s, 12)\n"
    "\n"
    "    def _series(self):\n"
    "        fb = self.fb\n"
    "        n = len(self.xs)\n"
    "        if self.mode == 1:\n"
    "            i = 0\n"
    "            while i < n:\n"
    "                px = self._mx(self.xs[i])\n"
    "                py = self._my(self.ys[i])\n"
    "                if self.px0 <= px < self.px0 + self.pw and self.py0 <= py < self.py0 + self.ph:\n"
    "                    fb.pixel(px, py, 1)\n"
    "                    fb.pixel(px + 1, py, 1)\n"
    "                    fb.pixel(px, py + 1, 1)\n"
    "                i += 1\n"
    "        else:\n"
    "            i = 1\n"
    "            while i < n:\n"
    "                x1 = self._mx(self.xs[i - 1])\n"
    "                y1 = self._my(self.ys[i - 1])\n"
    "                x2 = self._mx(self.xs[i])\n"
    "                y2 = self._my(self.ys[i])\n"
    "                fb.line(x1, y1, x2, y2, 1)\n"
    "                i += 1\n"
    "\n"
    "    def show(self):\n"
    "        self._bounds()\n"
    "        self._frame()\n"
    "        self._axes()\n"
    "        self._series()\n"
    "        lcd.text(4, 1, self.title, 12)\n"
    "        lcd.text(4, self.h - _BAR, \"ON: back\", 12)\n"
    "        lcd.blit(self.fb)\n"
    "        lcd.wait_key()\n"
    "        # after returning, the terminal is redrawn by the app on the next loop\n"
    "\n"
    "\n"
    "# ---------- module level API ----------\n"
    "def _g_():\n"
    "    global _g\n"
    "    if _g is None:\n"
    "        _g = _Graph()\n"
    "    return _g\n"
    "\n"
    "\n"
    "def clf():\n"
    "    _g_().clf()\n"
    "\n"
    "\n"
    "def plot(a, b=None, c=None, d=None):\n"
    "    _g_().plot(a, b, c, d)\n"
    "\n"
    "\n"
    "def scatter(x, y):\n"
    "    _g_().scatter(x, y)\n"
    "\n"
    "\n"
    "def axis(xmin, xmax, ymin, ymax):\n"
    "    _g_().axis(xmin, xmax, ymin, ymax)\n"
    "\n"
    "\n"
    "def title(s):\n"
    "    _g_().title(s)\n"
    "\n"
    "\n"
    "def show():\n"
    "    _g_().show()\n"
    "\n"
;
